### ISSUE TITLE
LUVLI loss cannot convergence

### ISSUE THREAD

**Issue by yeqi17** [abhi1kumar/MERL-RAV_dataset#2]
Thanks for the amazing work. I have tried to use the loss in the paper on the facial landmark project. However , I find the loss cannot convergence. In chapter 3.2.1 of the paper, if the predicted landmark's value equal to the target, the loss's T1 part will tends to negative infinity.（Σij will tends to zero).Could you please tell me the correct way to use the loss? ^_^

**Comment by abhi1kumar** [comment]
The code is now publicly available [here](https://github.com/abhi1kumar/LUVLi/). The code for the uncertainty in the loss is 
https://github.com/abhi1kumar/LUVLi/blob/master/loss/gaussian_loss.py

**Comment by flynnamy** [comment]
Where is the code? @abhi1kumar

**Comment by abhi1kumar** [comment]
> Where is the code? @abhi1kumar

I received an email from MERL saying that I should not re-host the repo since it violates MERL policies. So, I deleted the files  from the repo in the next commit.

The README of the [repo](https://github.com/abhi1kumar/LUVLi/) directs you to the [MERL website](https://www.merl.com/research/license/LUVLi). You should officially download the repo from the [MERL website](https://www.merl.com/research/license/LUVLi) after submitting your details.
